config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root :to => 'pages#index'

  resources :users
  resources :reservations
  resources :flights
  resources :aeroplanes

end

app/models/aeroplane.rb
# == Schema Information
#
# Table name: aeroplanes
#
#  id         :integer          not null, primary key
#  name       :string
#  rows       :string
#  columns    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Aeroplane < ActiveRecord::Base
  has_many :flights
end

app/controllers/aeroplanes_controller.rb
class AeroplanesController < ApplicationController
  before_action :set_aeroplane, only: [:show, :edit, :update, :destroy]

  # GET /aeroplanes
  # GET /aeroplanes.json
  def index
    @aeroplanes = Aeroplane.all
  end

  # GET /aeroplanes/1
  # GET /aeroplanes/1.json
  def show
  end

  # GET /aeroplanes/new
  def new
    @aeroplane = Aeroplane.new
  end

  # GET /aeroplanes/1/edit
  def edit
  end

  # POST /aeroplanes
  # POST /aeroplanes.json
  def create
    @aeroplane = Aeroplane.new(aeroplane_params)

    respond_to do |format|
      if @aeroplane.save
        format.html { redirect_to @aeroplane, notice: 'Aeroplane was successfully created.' }
        format.json { render :show, status: :created, location: @aeroplane }
      else
        format.html { render :new }
        format.json { render json: @aeroplane.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aeroplanes/1
  # PATCH/PUT /aeroplanes/1.json
  def update
    respond_to do |format|
      if @aeroplane.update(aeroplane_params)
        format.html { redirect_to @aeroplane, notice: 'Aeroplane was successfully updated.' }
        format.json { render :show, status: :ok, location: @aeroplane }
      else
        format.html { render :edit }
        format.json { render json: @aeroplane.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aeroplanes/1
  # DELETE /aeroplanes/1.json
  def destroy
    @aeroplane.destroy
    respond_to do |format|
      format.html { redirect_to aeroplanes_url, notice: 'Aeroplane was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aeroplane
      @aeroplane = Aeroplane.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aeroplane_params
      params.require(:aeroplane).permit(:name, :rows, :columns)
    end
end

app/helpers/aeroplanes_helper.rb
module AeroplanesHelper
end

app/views/aeroplanes/_form.html.erb
<%= form_for(@aeroplane) do |f| %>
  <% if @aeroplane.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aeroplane.errors.count, "error") %> prohibited this aeroplane from being saved:</h2>

      <ul>
      <% @aeroplane.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :rows %><br>
    <%= f.text_field :rows %>
  </div>
  <div class="field">
    <%= f.label :columns %><br>
    <%= f.text_field :columns %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/aeroplanes/edit.html.erb
<h1>Editing Aeroplane</h1>

<%= render 'form' %>

<%= link_to 'Show', @aeroplane %> |
<%= link_to 'Back', aeroplanes_path %>

app/views/aeroplanes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Aeroplanes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Rows</th>
      <th>Columns</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @aeroplanes.each do |aeroplane| %>
      <tr>
        <td><%= aeroplane.name %></td>
        <td><%= aeroplane.rows %></td>
        <td><%= aeroplane.columns %></td>
        <td><%= link_to 'Show', aeroplane %></td>
        <td><%= link_to 'Edit', edit_aeroplane_path(aeroplane) %></td>
        <td><%= link_to 'Destroy', aeroplane, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aeroplane', new_aeroplane_path %>

app/views/aeroplanes/new.html.erb
<h1>New Aeroplane</h1>

<%= render 'form' %>

<%= link_to 'Back', aeroplanes_path %>

app/views/aeroplanes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @aeroplane.name %>
</p>

<p>
  <strong>Rows:</strong>
  <%= @aeroplane.rows %>
</p>

<p>
  <strong>Columns:</strong>
  <%= @aeroplane.columns %>
</p>

<%= link_to 'Edit', edit_aeroplane_path(@aeroplane) %> |
<%= link_to 'Back', aeroplanes_path %>